---
name: Bundle API
on: push

jobs:
    validate:
      uses: dolphinsec/nodoc/.github/workflows/spec-validate.yaml@main
    bundle:
        uses: dolphinsec/nodoc/.github/workflows/spec-build.yaml@main
        needs: validate