---
name: Bundle API

on:
  push:
    branches:
      - main


jobs:
  validate:
    uses: dolphinsec/nodoc/.github/workflows/spec-validate.yaml@main
    permissions:
        contents: read
  bundle:
    uses: dolphinsec/nodoc/.github/workflows/spec-build.yaml@main
    needs: validate
    permissions:
        contents: read
  collection-validate:
    uses: dolphinsec/nodoc/.github/workflows/spec-validate-collection.yaml@main
    needs: bundle
    permissions:
        contents: read
    with:
      spec-artifact-name: ${{ needs.bundle.outputs.spec-artifact-name }}
