name: build postman collections with postman CLI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli@latest
      - name: Install OpenAPI-to-Postman
        run: npm install -g openapi-to-postmanv2@latest
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
  #    - name: Validate specification
  #      run: |
  #        redocly lint specification/openapi.yml
      - name: Bundle specification
        run: |
          redocly bundle -o build/openapi.yml
      - name: Generate stats
        run: |
          redocly stats --format=json > build/stats.json
      - name: Build postman collection
        run: >-
          openapi2postmanv2 -c postman_to_openapi.json
          -s build/openapi.yml -o postman/collections/collection.json
      - name: Commit collection
        run: |
          git config user.name 'collection-builder'
          git config user.email 'x-delfino@users.noreply.github.com'
          git add ./postman
          git commit -m "automated collection build"
          git push
      - name: Tag the repo
        id: tag
        run: |
          TAG=v$(date -Iseconds | sed 's/[T:\+]/-/g')
          echo "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git tag -a $TAG -m "Published version $TAG"
          git push origin $TAG
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/openapi.yml
            build/stats.json
