---
name: Release API definition

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  bundle:
    uses: dolphinsec/nodoc/.github/workflows/spec-build.yaml@main
    permissions:
      contents: read
  
  create-release:
    name: Create release
    needs: bundle
    uses: dolphinsec/nodoc/.github/workflows/spec-publish-postman.yaml@main
    permissions:
      contents: write
    with:
      spec-artifact-name: '${{ needs.bundle.outputs.spec-artifact-name }}'
      stats-artifact-name: '${{ needs.bundle.outputs.stats-artifact-name }}'
      api-root-path: 'specification/openapi.yml'
      release-tag: ${{ github.ref_name }}
      postman-api-id: ${{ vars.POSTMANAPIID }}
      postman-collection-path: 'postman/collections/Ibiza\ IAM.json'
    secrets:
      postman-api-key: ${{ secrets.POSTMANAPIKEY }}
