---
name: Validate OpenAPI Spec

permissions: {}

on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    uses: dolphinsec/nodoc/.github/workflows/spec-validate.yaml@main
    permissions:
        contents: read